# USER_TABLE

GET http://localhost:8000/user

###
POST http://localhost:8000/user
content-type:application/json

{
    "firstName": "Binderiya",
    "lastName":"Tsogt",
    "birthDate":"2000-03-05",
    "email": "binderiytsogthers@gmail.com",
    "phone": "1111112",
    "password": "",
    "imageUrl":""

}

###
GET http://localhost:8000/user/

###
DELETE http://localhost:8000/user/id

###
PATCH http://localhost:8000/user/id
Content-Type: application/json

{
    "name": "Altankhuyag Javkhlant",
    "email": "enrosek95@gmail.com",
    "number": 88916562,
    "address": "Crystal Town"
}
###

# CATEGORY_TABLE

GET http://localhost:8000/category

###
GET http://localhost:8000/category/3



###
POST http://localhost:8000/category
Content-Type: application/json

{
    "name":"Accessories",
    "slug":"accessories",
    "imageUrl":"",
    "productCount":1
}

### 
DELETE http://localhost:8000/category/3

###
PATCH http://localhost:8000/category/4
Content-Type: application/json

{
    "name":"Hat",
    "slug":"hat",
    "imageUrl":"",
    "productCount":1
}
###

# PRODUCT_TABLE
GET http://localhost:8000/product

###
GET http://localhost:8000/product/1

###
POST http://localhost:8000/product
Content-Type: application/json

{
    "name":"Gucci Princetown Crocodile Slipper with Double G",
    "description":"",
    "price":2650
}

###
DELETE http://localhost:8000/product/2

###
PATCH http://localhost:8000/product/3
Content-Type: application/json

{
    "name":"Gucci Princetown Crocodile Slipper with Double G",
    "description":"",
    "price":2600
}