GET http://localhost:8000/user

###

POST http://localhost:8000/user
content-type:application/json

{
    "name": "Tsogt Binderiya",
    "email": "binderiyatsogthers@gmail.com",
    "number": "00000000",
    "address": ""
}

###

GET http://localhost:8000/user/1

###

DELETE http://localhost:8000/user/id

###

PATCH http://localhost:8000/user/id
Content-Type: application/json

{
    "name": "Altankhuyag Javkhlant",
    "email": "enrosek95@gmail.com",
    "number": 88916562,
    "address": "Crystal Town"
}

